<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Lifespan.Tests</RootNamespace>
    <AssemblyName>Lifespan.Tests</AssemblyName>
    <ShelteredSmmRoot Condition="'$(ShelteredSmmRoot)' == ''">D:\SteamLibrary\steamapps\common\Sheltered\SMM</ShelteredSmmRoot>
    <ShelteredModsRoot Condition="'$(ShelteredModsRoot)' == ''">$(ShelteredSmmRoot)</ShelteredModsRoot>
    <ShelteredManagedRoot Condition="'$(ShelteredManagedRoot)' == ''">D:\SteamLibrary\steamapps\common\Sheltered\Sheltered_Data\Managed</ShelteredManagedRoot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="Moq" Version="4.18.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lifespan\Lifespan.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(ShelteredSmmRoot)\bin\0Harmony.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ShelteredManagedRoot)\Assembly-CSharp.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ModAPI">
      <HintPath>$(ShelteredModsRoot)\ModAPI.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ShelteredAPI">
      <HintPath>$(ShelteredModsRoot)\ShelteredAPI.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ShelteredManagedRoot)\UnityEngine.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
