<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Lifespan.Tests</RootNamespace>
    <AssemblyName>Lifespan.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="Moq" Version="4.18.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lifespan\Lifespan.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>D:\SteamLibrary\steamapps\common\Sheltered\SMM\bin\0Harmony.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\SteamLibrary\steamapps\common\Sheltered\Sheltered_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ModAPI">
      <HintPath>D:\SteamLibrary\steamapps\common\Sheltered\SMM\ModAPI.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>D:\SteamLibrary\steamapps\common\Sheltered\Sheltered_Data\Managed\UnityEngine.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
